{% set name = "Pymagej" %}
{% set version = "0.2.1" %}
{% set sha256 = "e0b4e8266423e5d8648920219985bdd59d6f22a7e89bc34f0b40a473399aba3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy

test:
  imports:
    - pymagej

about:
  home: https://github.com/Jhsmit/PymageJ
  license: GPL-2.0-or-later
  license_file: LICENSE.md
  summary: Python tools for ImageJ

extra:
  recipe-maintainers:
    - jakirkham
    - jhsmit
