{% set name = "PymageJ" %}
{% set version = "0.1" %}
{% set sha256 = "a18103bbb773b88542fd84f7dffd36d7310d9644ac44e9bc6f2d5b049aa52f33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1003
  skip: true  # [not py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  imports:
    - PymageJ

about:
  home: https://github.com/Jhsmit/PymageJ
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python tools for ImageJ

extra:
  recipe-maintainers:
    - jakirkham
    - jhsmit
