travis:
  secure:
    BINSTAR_TOKEN: bvryqathQLdL/lyiJiboGMvdhjF9QG6F4SEksNWR3+A0RHaI/cL6E2M2rzbeuISR+llUOt5IRQa+YEkIp4kTWqPm9YMFmgGAbqvQgc346Ok9WgPWqZzmmUKV5D3yvPLT/SSNFc/dZnaQ5tyN6ywhla35Jgf6s2ud1HETOixvgUWaFe+f1b9/tf422z2su987SAYh6yKkY86ppX8tJMIYlIt0QAOJSwhHa97w30Lvgr/fOG3rSDsGwiqshdvxxA5R4A02hojs0uxKu+Ogycf+mZVKf46Fx8R3tuJo40iz2Fie/TQJkr2hLiray5yyoH7dVgQg+mAlhGQRS1jev1fkZTuUJNfi97Zk1aI2SUL20KKVsj1aZ7ziTHug7fCBEpBI/dxmYbmG3IDh4CLAIhvw0MRk+8nhXVEEZ8Eqde3wa+L8cffVVNwl6t+YD5eWeHKmX/0VlzIfs+LIyirriVkkUTYicTPaMjb5wjftN1qQ7GcS7wzaPsd5J5aHi2DUyBPqjGgYSOqhPcUamQNwdIn5fDiqlohfVnFmrkVhhg2OF9EFXvt8sdpg8z8fwUZrlHCUExylxCFeTbgou7E+l3QNGPiTYx0wjxNRfetTZFN4y2jFZQtYpTyQjgvP3xsoBmlnXWL6ds4Q+ANMEIOqF3B1OWM2X96pjy9UzfJZD6LzGSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
